import { getPrismaClient } from "@/infrastructure/database/prisma";
import { dashboardData, evaluateAchievements, listMilestones } from "@/infrastructure/product/progress-repository";
import { PageTitle, Panel, Notice, inputClass, buttonClass } from "@/app/workflows/components";
import { createMilestoneAction, createAchievementAction, updateMilestoneAction, deleteMilestoneAction } from "@/app/workflows/actions";
export const dynamic = "force-dynamic";
function Bars({ title, buckets }: { title: string; buckets: Array<{ period: string; minutes: number }> }) {
  const maximum = Math.max(1, ...buckets.map((bucket) => bucket.minutes));
  return <section className="mb-5 rounded-xl border border-stone-300 bg-white p-4 sm:p-5"><h2 className="mb-3 text-lg font-semibold">{title}</h2><div className="space-y-2">{buckets.map((bucket) => <div key={bucket.period} className="grid grid-cols-[6rem_1fr_4rem] items-center gap-2 text-xs"><span>{bucket.period}</span><div className="h-4 rounded bg-stone-100"><div aria-label={`${bucket.period}: ${bucket.minutes} minutes`} className="h-4 rounded bg-stone-700" style={{ width: `${bucket.minutes ? Math.max(2, bucket.minutes * 100 / maximum) : 0}%` }}/></div><span className="text-right">{bucket.minutes} min</span></div>)}</div></section>;
}
export default async function ProgressPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const db = getPrismaClient();
  const [data, evaluated, milestoneData, params] = await Promise.all([dashboardData(db), evaluateAchievements(db), listMilestones(db), searchParams]);
  const today = data.today;
  const monthStart = `${today.slice(0,7)}-01`;
  const first = new Date(`${monthStart}T00:00:00Z`);
  const offset = (first.getUTCDay()+6)%7;
  const cells = Array.from({length: new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate()},(_,i)=>i+1);
  const practicedCategories = data.categoryTotals.filter((category)=>category.minutes>0);
  return <><PageTitle title="Progress" description="Historical measures from your goals and records. No overall mastery percentage is calculated."/><Notice error={params.error} success={params.success}/>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Current streak",`${data.currentStreak} ${data.currentStreak === 1 ? "day" : "days"}`],["Longest streak",`${data.longestStreak} ${data.longestStreak === 1 ? "day" : "days"}`],["Practice today",data.durations.today+" min"],["Practice this week",data.durations.week+" min"],["Practice this month",data.durations.month+" min"],["Practice this year",data.durations.year+" min"],["Lifetime practice",data.durations.lifetime+" min"],["Practice days (31d)",data.practiceDaysThisMonth]].map(([label,value])=><div key={label} className="rounded border bg-white p-4"><p className="text-sm text-stone-600">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div>
    <Panel title="Current planning period">{data.activePeriod ? <><p>Period #{data.activePeriod.sequenceNo} · {data.activePeriod.startOn.toISOString().slice(0,10)} · {data.activePeriod.goals.filter(g=>g.status==="COMPLETED").length}/{data.activePeriod.goals.length} goals complete</p><ul className="mt-2 list-disc pl-6">{data.activePeriod.goals.map(g=><li key={g.id}>{g.kind}: {g.title} — {g.status.toLowerCase().replaceAll("_"," ")}</li>)}</ul></> : <p>No planning periods yet.</p>}<p className="mt-2">Completed learning items: {data.completedLearningItems}; lessons: {data.completedLessons}; songs: {data.completedSongs}.</p></Panel>
    <Panel title="Practice by category">{practicedCategories.length ? practicedCategories.map((c,i)=><p key={c.id}>{c.name}: {c.minutes} minutes{i===0?" · most practiced":i===practicedCategories.length-1?" · least practiced":""}</p>) : <p>No practice records have category attribution yet. Choose a category when logging practice to see activity here.</p>}{data.ratedCategories.map(c=><p key={c.name}>{c.name}: average rating {c.averageRating.toFixed(1)}/5</p>)}</Panel>
    <Bars title="Daily practice · 14 days" buckets={data.dailyPracticeChart}/><Bars title="Weekly practice · 12 weeks" buckets={data.weeklyPracticeChart}/><Bars title="Monthly practice · 12 months" buckets={data.monthlyPracticeChart}/><Bars title="Yearly practice · historical" buckets={data.yearlyPracticeChart}/>
    <Panel title="Main goal completion by planning period">{data.goalCompletionSeries.map((period)=><p key={period.period}>{period.period}: {period.percent}%</p>)}</Panel>
    <Panel title="Unfinished goals from previous periods">{data.unfinishedPreviousGoals.length ? data.unfinishedPreviousGoals.map((goal)=><p key={goal.id}>Period #{goal.periodSequence}: {goal.kind} · {goal.title} ({goal.status.toLowerCase().replaceAll("_"," ")})</p>) : <p>No unfinished goals from previous periods.</p>}</Panel>
    <Panel title="Recent optional review cycles">{data.reviewCycles.map((cycle)=><p key={cycle.id}>Cycle {cycle.cycleNumber} · {cycle.decision.toLowerCase().replaceAll("_"," ")}{cycle.review ? ` · Review ${cycle.review.status.toLowerCase()}` : ""}</p>)}</Panel>
    <Panel title={`Practice calendar · ${today.slice(0,7)}`}><div className="grid grid-cols-7 gap-1 text-center text-xs">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=><strong key={d}>{d}</strong>)}{Array.from({length:offset},(_,i)=><span key={`blank${i}`}/>)}{cells.map(day=>{const key=`${today.slice(0,7)}-${String(day).padStart(2,"0")}`;const info=data.practiceDates.filter(x=>x.practicedOn.toISOString().slice(0,10)===key);const minutes=info.reduce((sum,x)=>sum+x.durationMinutes,0);return <span key={key} title={`${key}: ${minutes} minutes`} className={`rounded border p-2 ${minutes?"bg-green-100":"bg-white"}`}>{day}{minutes>0&&<small className="block">{minutes}m</small>}</span>})}</div></Panel>
    <Panel title="Login days (configured timezone)"><p className="mb-2 text-sm text-stone-600">The streak uses stored first-login instants and your current timezone preference.</p><div className="flex flex-wrap gap-2">{data.loginDates.map(d=><span key={d} className="rounded border px-2 py-1 text-sm">{d}</span>)}</div></Panel>
    <Panel title="Achievement definitions" id="achievements"><form action={createAchievementAction} className="grid gap-2 sm:grid-cols-3"><label className="grid gap-1 text-xs">Key<input required name="key" className={inputClass}/></label><label className="grid gap-1 text-xs">Name<input required name="name" className={inputClass}/></label><label className="grid gap-1 text-xs">Metric<select name="evaluatorKey" className={inputClass}>{["count_practices","completed_lessons","completed_songs","completed_weeks","practice_minutes","completed_reviews","login_streak"].map(k=><option key={k}>{k}</option>)}</select></label><label className="grid gap-1 text-xs">Threshold<input required type="number" min="1" name="threshold" className={inputClass}/></label><input type="hidden" name="isActive" value="true"/><label className="grid gap-1 text-xs">Description<input name="description" className={inputClass}/></label><button className={`${buttonClass} self-end`}>Add achievement rule</button></form><ul className="mt-4 list-disc pl-6">{evaluated.definitions.map(d=><li key={d.id}>{d.name}{evaluated.awards.some(a=>a.achievementDefinitionId===d.id)?" — awarded":""}</li>)}</ul></Panel>
    <Panel title="Personal milestones"><form action={createMilestoneAction} className="mb-4 grid gap-2 sm:grid-cols-3"><input type="hidden" name="returnTo" value="/progress"/><label className="grid gap-1 text-xs">Title<input required name="title" className={inputClass}/></label><label className="grid gap-1 text-xs">Date<input required type="date" name="happenedOn" defaultValue={today} className={inputClass}/></label><label className="grid gap-1 text-xs">Related category<select name="categoryId" className={inputClass}><option value="">None</option>{milestoneData.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="grid gap-1 text-xs">Description<input name="description" className={inputClass}/></label><button className={`${buttonClass} self-end`}>Add milestone</button></form>{milestoneData.milestones.map(m=><div key={m.id} className="border-t py-3"><form action={updateMilestoneAction} className="flex flex-wrap items-end gap-2"><input type="hidden" name="id" value={m.id}/><label className="grid gap-1 text-xs">Title<input name="title" defaultValue={m.title} className={inputClass}/></label><label className="grid gap-1 text-xs">Date<input type="date" name="happenedOn" defaultValue={m.happenedOn.toISOString().slice(0,10)} className={inputClass}/></label><label className="grid gap-1 text-xs">Category<select name="categoryId" defaultValue={m.categoryId ?? ""} className={inputClass}><option value="">None</option>{milestoneData.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="grid gap-1 text-xs">Description<input name="description" defaultValue={m.description ?? ""} className={inputClass}/></label><button className={buttonClass}>Save</button></form><form action={deleteMilestoneAction} className="mt-2"><input type="hidden" name="id" value={m.id}/><button className="rounded border px-3 py-2 text-sm">Delete milestone</button></form></div>)}</Panel>
    <Panel title="Timeline">{data.timeline.map((e,i)=><p key={`${e.id}-${i}`} className="border-b py-2">{e.date} · {e.kind} · {e.title}</p>)}</Panel>
  </>;
}
