import { getPrismaClient } from "@/infrastructure/database/prisma";
import { listSongs } from "@/infrastructure/product/activity-repository";
import { PageTitle, Panel, Notice, inputClass, buttonClass, dangerButtonClass } from "@/app/workflows/components";
import { createSongAction, createSectionAction, updateSongAction, updateSectionAction, deleteSongAction, deleteSectionAction } from "@/app/workflows/actions";
export const dynamic = "force-dynamic";
export default async function SongsPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const [data, params] = await Promise.all([listSongs(getPrismaClient()), searchParams]);
  const today = new Date().toISOString().slice(0,10);
  return <><PageTitle title="Songs and repertoire" description="Song difficulty and progress are entered by you."/><Notice error={params.error} success={params.success}/>
    <Panel title="Add song"><form action={createSongAction} className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">Title<input required name="title" className={inputClass}/></label><label className="grid gap-1 text-sm">Composer<input name="composer" className={inputClass}/></label><label className="grid gap-1 text-sm">Category<select name="categoryId" className={inputClass}><option value="">None</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="grid gap-1 text-sm">Difficulty (1–5)<select name="difficulty" className={inputClass}><option value="">Not rated</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label className="grid gap-1 text-sm">Added<input required type="date" name="addedOn" defaultValue={today} className={inputClass}/></label><label className="grid gap-1 text-sm">Status<select name="status" className={inputClass}><option value="NOT_STARTED">Not started</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></select></label><button className={`${buttonClass} justify-self-start`}>Add song</button></form></Panel>
    {data.songs.map(song=><Panel key={song.id} title={`${song.title}${song.composer ? ` — ${song.composer}` : ""}`}>
      <form action={updateSongAction} className="grid gap-3 sm:grid-cols-3"><input type="hidden" name="id" value={song.id}/><input type="hidden" name="title" value={song.title}/><input type="hidden" name="composer" value={song.composer ?? ""}/><input type="hidden" name="categoryId" value={song.categoryId ?? ""}/><input type="hidden" name="addedOn" value={song.addedOn.toISOString().slice(0,10)}/>
        <label className="grid gap-1 text-sm">Difficulty<select name="difficulty" defaultValue={song.difficulty ?? ""} className={inputClass}><option value="">—</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label className="grid gap-1 text-sm">Status<select name="status" defaultValue={song.status} className={inputClass}><option value="NOT_STARTED">Not started</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></select></label><label className="grid gap-1 text-sm">Started<input type="date" name="startedOn" defaultValue={song.startedOn?.toISOString().slice(0,10) ?? ""} className={inputClass}/></label><label className="grid gap-1 text-sm">Completed<input type="date" name="completedOn" defaultValue={song.completedOn?.toISOString().slice(0,10) ?? ""} className={inputClass}/></label><label className="grid gap-1 text-sm">Rating<select name="rating" defaultValue={song.rating ?? ""} className={inputClass}><option value="">—</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label className="grid gap-1 text-sm">Notes<input name="notes" defaultValue={song.notes ?? ""} className={inputClass}/></label><button className={`${buttonClass} justify-self-start`}>Save song progress</button><button formAction={deleteSongAction} name="id" value={song.id} className={dangerButtonClass}>Delete / archive</button></form>
      <h3 className="mt-4 font-medium">Sections</h3>{song.sections.map(section=><div key={section.id} className="my-2 rounded border p-3"><form action={updateSectionAction} className="flex flex-wrap items-end gap-2"><input type="hidden" name="songId" value={song.id}/><input type="hidden" name="id" value={section.id}/><label className="grid gap-1 text-xs">Section<input name="title" defaultValue={section.title} className={inputClass}/></label><label className="grid gap-1 text-xs">Order<input type="number" name="sortOrder" defaultValue={section.sortOrder} className={inputClass}/></label><label className="grid gap-1 text-xs">Status<select name="status" defaultValue={section.status} className={inputClass}><option value="NOT_STARTED">Not started</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></select></label><label className="grid gap-1 text-xs">Started<input type="date" name="startedOn" defaultValue={section.startedOn?.toISOString().slice(0,10) ?? ""} className={inputClass}/></label><label className="grid gap-1 text-xs">Completed<input type="date" name="completedOn" defaultValue={section.completedOn?.toISOString().slice(0,10) ?? ""} className={inputClass}/></label><input type="hidden" name="rating" value={section.rating ?? ""}/><input type="hidden" name="notes" value={section.notes ?? ""}/><button className={buttonClass}>Save section</button><button formAction={deleteSectionAction} name="id" value={section.id} className={dangerButtonClass}>Delete / archive</button></form></div>)}
      <form action={createSectionAction} className="mt-3 flex flex-wrap items-end gap-2"><input type="hidden" name="songId" value={song.id}/><label className="grid gap-1 text-sm">New section<input required name="title" className={inputClass}/></label><label className="grid gap-1 text-sm">Order<input required type="number" min="0" name="sortOrder" defaultValue={song.sections.length} className={inputClass}/></label><input type="hidden" name="status" value="NOT_STARTED"/><button className={buttonClass}>Add section</button></form>
    </Panel>)}
  </>;
}
